# site settings
title: Misstravel
email: misstravel0921@gmail.com
line: misstravel0921
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://misstravel.me" # the base hostname & protocol for your site
author: 密式旅行
phone: 0905108958
description: "密式旅行露營區，位於苗栗泰安鄕，提供露營、小木屋、套房等多種住宿選擇，園內還提供桌遊咖啡廳、兒童遊戲室、兒童沙坑等空間。"
lang: zh-TW
locale: zh_TW
logo: /assets/images/logo.jpg
role_url: "infos/2022-10-06-roles.html"
account_url: "infos/2022-10-06-account.html"
set_menu_url: "infos/2022-10-06-set-menu-info.html"
menu_url: "infos/2022-10-06-menu.html"
meta_title: "密式旅行露營區，苗栗泰安鄕小木屋露營區"
meta_description: "密式旅行露營區，位於苗栗泰安鄕，提供露營、小木屋、套房等多種住宿選擇，園內還提供桌遊咖啡廳、兒童遊戲室、兒童沙坑等空間，是個非常適合闔家前往的親子露營區。桌遊咖啡廳除了販售輕食、咖啡以外，也有提供免費的桌遊教學。雲海、夕陽等美景也經常造訪，竹林秘境車程十分鐘即可到達。"

# homepage tiles
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  Facebook: https://www.facebook.com/misstravel0921
  Instagram: https://www.instagram.com/misstravel_miaoli
  Github: https://github.com/Lawa0921/Lawa0921.github.io

# social media for SEO
social:
  name: 密式旅行
  links:
    - https://www.facebook.com/misstravel0921
    - https://www.instagram.com/misstravel_miaoli

# default social image
defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/rooms.jpg

collections:
  rooms:
    output: true
  infos:
    output: true
  announcements:
    output: true

# build settings
markdown: kramdown
kramdown:
  input: GFM

sass:
  load_paths:
    - _sass
  style: compressed
  quiet_deps: true # Suppress deprecation warnings from dependencies
  silence_deprecations: ['import'] # Silence specific deprecation warnings

# server settings
port: 4200

# plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
