# site settings
title: Misstravel
email: misstravel0921@gmail.com
line: misstravel0921
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
phone: 0905108958
role_url: "infos/2022-10-06-roles.html"
account_url: "infos/2022-10-06-account.html"
set_menu_url: "infos/2022-10-06-set-menu-info.html"
menu_url: "infos/2022-10-06-menu.html"
meta_title: "密式旅行露營區，苗栗泰安鄉小木屋露營區"
meta_description: "密式旅行露營區，位於苗栗泰安鄉，提供露營、小木屋、套房等多種住宿選擇，園內還提供桌遊咖啡廳、兒童遊戲室、兒童沙坑等空間，是個非常適合闔家前往的親子露營區。桌遊咖啡廳除了販售輕食、咖啡以外，也有提供免費的桌遊教學。雲海、夕陽等美景也經常造訪，竹林秘境車程十分鐘即可到達。"

# homepage tiles
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  Facebook: https://www.facebook.com/misstravel0921
  Instagram: https://www.instagram.com/misstravel_miaoli
  Github: https://github.com/Lawa0921/Lawa0921.github.io

collections:
  rooms:
    output: true
  infos:
    output: true
  announcements:
    output: true

# build settings
markdown: kramdown
kramdown:
  input: GFM

sass:
  load_paths:
    - _sass
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 

images_url:
  booking: https://drive.google.com/uc?id=1jH8_uGG-juxWa4uDzeYemLi7vyGwyq8w
  map_info: https://drive.google.com/uc?id=1k73GQTR7svYiFoSL2g1Lgf6Tn7xYEe9Z
  booking_announcement: https://drive.google.com/uc?id=1lmie0tSblSlbv21TLqRvKcrEprnynfwK
  campsite_1:
    - url: https://drive.google.com/uc?id=1ar-Sxw-M7XYoqUOusHUcdynHXerwygQu
    - url: https://drive.google.com/uc?id=1A9gRQ0ZoNbErqcr00pYDaYI720lJoGkd
    - url: https://drive.google.com/uc?id=1d1jK81egbzpoy1b0pD-RsCCx1dar6wFE
    - url: https://drive.google.com/uc?id=1d_YaBga3kTf1uCmoO9ooHj9Axc97Wlhe
    - url: https://drive.google.com/uc?id=1-5zcQOaFCyjTXbqzNl8BdP9ASJ7Z1vrr
    - url: https://drive.google.com/uc?id=1NAPapvV0vEkYR55mcEK2rCwBs_q5OitS
    - url: https://drive.google.com/uc?id=1y9S-QF2nJPA674nHnNsi14f9MnqNsFwp
    - url: https://drive.google.com/uc?id=1uYSQrivtcjJvyd3-Qq2jxW1VHwnJPW8-
    - url: https://drive.google.com/uc?id=1bVVFagDIyPuLZh1-Le_oABklu_wF5a-V
    - url: https://drive.google.com/uc?id=1USSGoEjmeOHDiLUICAhO3-eRxP1Nb0FY
    - url: https://drive.google.com/uc?id=1twxz9IH8II05EJCGaHRhciJ9cRosaUAh
    - url: https://drive.google.com/uc?id=1ztyj5xw3k5R420oCrfbnaa_1CxdNmrnN
    - url: https://drive.google.com/uc?id=1AHA5uEbf4jMSykfYg9u9qaOMBhW9Kyy1
    - url: https://drive.google.com/uc?id=1p8HWuZA8xDUVws7VmPwAvpkDknvOoepG
    - url: https://drive.google.com/uc?id=15mLbB-4TiamTKnFiTCJngYhkD9sbbaA4
    - url: https://drive.google.com/uc?id=1RrGbfmMigAcd58vSaQD8sjOlNMSfsBnU
    - url: https://drive.google.com/uc?id=1k73GQTR7svYiFoSL2g1Lgf6Tn7xYEe9Z
    - url: https://drive.google.com/uc?id=1lmie0tSblSlbv21TLqRvKcrEprnynfwK
  campsite_2:
    - url: https://drive.google.com/uc?id=1hPLDrXgQxV-rewOt84phvTaqGNcvnaZt
    - url: https://drive.google.com/uc?id=1JYDAXB7tVoQkknSl9fA0pOIkb49QpmaG
    - url: https://drive.google.com/uc?id=1YNFohQwzoloUhPTNuiu9c-QLCXYafIZt
    - url: https://drive.google.com/uc?id=1mNp0_4TjQBJmIBvT4mR6B8c5QYiIfaEL
    - url: https://drive.google.com/uc?id=1cooaavAx0a5Xbyi0uV4jxPrsX2TfuJTK
    - url: https://drive.google.com/uc?id=1LjJsG-F_ceq-klIsmqnHeP4RwESle8WE
    - url: https://drive.google.com/uc?id=1CzVWKN5ccSNVVLX2aVx-ulYSJU3iBLdi
    - url: https://drive.google.com/uc?id=1k73GQTR7svYiFoSL2g1Lgf6Tn7xYEe9Z
    - url: https://drive.google.com/uc?id=1lmie0tSblSlbv21TLqRvKcrEprnynfwK
  campsite_3:
    - url: https://drive.google.com/uc?id=1kmW7VPfW15Trqhs4fFcvXTjVt2VAPFVL
    - url: https://drive.google.com/uc?id=1W0p2hjy_-Yeaseab3l3xgp0jexQcURbY
    - url: https://drive.google.com/uc?id=1bIuVo28Pl7btLiKnoFWWaVPqWXFdey4T
    - url: https://drive.google.com/uc?id=1_5BzHZtK74deUm_HxACOaqnUlaYcFFSu
    - url: https://drive.google.com/uc?id=13_2uzhftuAdenKlSBQDIjrQ4mnN1f0TO
    - url: https://drive.google.com/uc?id=1MsC5LDKOqmx4bG1BdEH857DggDbUk0na
    - url: https://drive.google.com/uc?id=1ND1934iBBtxchsTC4Xbkay4p7fNVV7hn
    - url: https://drive.google.com/uc?id=1psc056BDFbz4u24PJakeubAVLyQExrCZ
    - url: https://drive.google.com/uc?id=1H35y3rxHrWEzcVshm4AVv8SpCcBfoYyo
    - url: https://drive.google.com/uc?id=1k73GQTR7svYiFoSL2g1Lgf6Tn7xYEe9Z
    - url: https://drive.google.com/uc?id=1lmie0tSblSlbv21TLqRvKcrEprnynfwK
  log_cabin_1:
    - url: https://drive.google.com/uc?id=1rKBY1s5JgGImIot5mDq3n6zOY-vFNwLk
    - url: https://drive.google.com/uc?id=1zXFIV6ZUeYN2hRXWkuIsYSR8OO6J-XoO
    - url: https://drive.google.com/uc?id=1Y45KYP_4nb6vPrqW7ugkMBrkClQuYFf_
    - url: https://drive.google.com/uc?id=103WvlZMHD4dmOrQPYDxL1K_hVbP1HPmt
    - url: https://drive.google.com/uc?id=1iYyzxGBknf0UEfcdN_3AGhJTBJrwzHie
    - url: https://drive.google.com/uc?id=15rzeAmBftv36rORtzZna41YcjR3Ru3UK
    - url: https://drive.google.com/uc?id=1utd8wVH1JKZl42MJuyem4s0njDeuOziG
    - url: https://drive.google.com/uc?id=1KwUXN0L9gvSjgO43kW9b8tR15E6ZInU5
    - url: https://drive.google.com/uc?id=1BNYaGtYa2c_xHUt8O8v3jmpgjVmigF2L
    - url: https://drive.google.com/uc?id=18k-aTifSidgQictfLinruiLHPY6lkjEU
    - url: https://drive.google.com/uc?id=1HLM9kOjLsML86bUW7A1uQO5zFafEm874
    - url: https://drive.google.com/uc?id=1FncMvKe1nbn--L7TlF8RQdxS7d-hTscf
    - url: https://drive.google.com/uc?id=1k73GQTR7svYiFoSL2g1Lgf6Tn7xYEe9Z
    - url: https://drive.google.com/uc?id=1lmie0tSblSlbv21TLqRvKcrEprnynfwK
  log_cabin_2:
    - url: https://drive.google.com/uc?id=1y-1pUxq3pScIpD2x6dalA0256WFlijux
    - url: https://drive.google.com/uc?id=1hedU0S7C9PEkJxK5py4srjV4PQw5EyIX
    - url: https://drive.google.com/uc?id=1eTnPoP9CUJQa9hF_sIHBviwxNXjqMYFJ
    - url: https://drive.google.com/uc?id=1aDfC6Sv09HkAdQFdmaGO_mVJvNLEDUpY
    - url: https://drive.google.com/uc?id=1VGZtmzR2RWkrH87uLXZPSFqnX9zfiusO
    - url: https://drive.google.com/uc?id=1dTjX6pD-s0kcHVcgKxfr3ReHM2iZtfLH
    - url: https://drive.google.com/uc?id=1a9JXf9W0_0zSYUwaneWZJCPUWJ1JqbKV
    - url: https://drive.google.com/uc?id=1HOOAfHVFSJkFXziKl9cdvvmucnWOt5zK
    - url: https://drive.google.com/uc?id=1M03LHQvVyUPai7dNdBoW939fG5KGW0ZS
    - url: https://drive.google.com/uc?id=1k73GQTR7svYiFoSL2g1Lgf6Tn7xYEe9Z
    - url: https://drive.google.com/uc?id=1lmie0tSblSlbv21TLqRvKcrEprnynfwK
  log_cabin_3:
    - url: https://drive.google.com/uc?id=1W57QQgL9xgtQGtOjLRbZpcCPgBv_ffPv
    - url: https://drive.google.com/uc?id=1oG85dzm4RHC4LbcEe6nKcKKIDtrjwOCj
    - url: https://drive.google.com/uc?id=13DkvbtOzV2fjI46ufxglc2K64L8Egzf0
    - url: https://drive.google.com/uc?id=1z3cTTLpUA5zNmwSX01yiXLPTC-p-EzId
    - url: https://drive.google.com/uc?id=1Nld-8oYLS0vURT6BzDrX9yi1LTQn4Dbf
    - url: https://drive.google.com/uc?id=1mA5tYOjLZlZGM_bkcCfim8OPf_9lMKtc
    - url: https://drive.google.com/uc?id=1xvTZQthx60Sqz__KJbi6HF5IfGpFkO9b
    - url: https://drive.google.com/uc?id=194Z7T3RRbajh1cOmhfd1LL1y0lF6Rh9f
    - url: https://drive.google.com/uc?id=1WV7c_q8A_GQ-YMykJjtS1oplVyWI3lST
    - url: https://drive.google.com/uc?id=1WfxzXfDurxqDSUb-PPBsk0rJFit0j7S4
    - url: https://drive.google.com/uc?id=1Wyid8iDLkLKjPNwHYRwPaCmeWgPqRIVd
    - url: https://drive.google.com/uc?id=1bYbJLKRo5JgZdrab-54N-GFpol43WRxU
    - url: https://drive.google.com/uc?id=1k73GQTR7svYiFoSL2g1Lgf6Tn7xYEe9Z
    - url: https://drive.google.com/uc?id=1lmie0tSblSlbv21TLqRvKcrEprnynfwK
  log_cabin_4:
    - url: https://drive.google.com/uc?id=1e2NFP0vn-ozraChDqeHzaQoUa0UaSuBN
    - url: https://drive.google.com/uc?id=17gYnoB8596C4zS5HNd8jYiafi-zjMT91
    - url: https://drive.google.com/uc?id=1JXyiyRRqX4XPoaLI8i5LxrlsaXOxdapL
    - url: https://drive.google.com/uc?id=1d6w4hlACwjD4ZcdTLbtDLtUN71ikUPiW
    - url: https://drive.google.com/uc?id=14RmIcHcUBTEnTPid62_mQMw9SXnqphud
    - url: https://drive.google.com/uc?id=16ElhNsqvx4Pn28aEEWmwsPErst1ZkDdo
    - url: https://drive.google.com/uc?id=1r5mT7RYjKI-CnDhQBaUG9H4yLvZg4Mru
    - url: https://drive.google.com/uc?id=1sHL6Nb8kBIWMyI2UeiGnjtCqq0KEx-5-
    - url: https://drive.google.com/uc?id=1i09oIQNsxHF5lBlple3yXdMKqF-z6PzZ
    - url: https://drive.google.com/uc?id=10pnE4Q5FPKqh-2STz44fLnyhMqQ8Kf34
    - url: https://drive.google.com/uc?id=1k73GQTR7svYiFoSL2g1Lgf6Tn7xYEe9Z
    - url: https://drive.google.com/uc?id=1lmie0tSblSlbv21TLqRvKcrEprnynfwK
  suite_1:
    - url: https://drive.google.com/uc?id=1DvHX_hpwtkpKZHUlnCOK7yKLzw7dhCwF
    - url: https://drive.google.com/uc?id=1DF8cXkIivWGlFicomIcmX1ayZtHHFAJy
    - url: https://drive.google.com/uc?id=1VeHYF11i7PZfzuxF9uDufGASJ4M1oZJV
    - url: https://drive.google.com/uc?id=1UY10jH_J0GAoJxxKpf_HLDZdoHVZvfWF
    - url: https://drive.google.com/uc?id=1y2cOS2hk9NooLrSaOXi_V1bZIabFFXj9
    - url: https://drive.google.com/uc?id=1JG0ZCYSSIAki_JXUT0ViqlDShbdYKQfz
    - url: https://drive.google.com/uc?id=1MuqvKnCx8WpujLjEnOX9rfqYNpgPj_cL
    - url: https://drive.google.com/uc?id=1S_E67hAzJiZv6UI-pbUGrQQYMXcGOk66
    - url: https://drive.google.com/uc?id=19bkXryk0Ie2sfLcVf5ePqBEeGdmQsOvu
    - url: https://drive.google.com/uc?id=14Xa8Mm78gkEOI-71vGJ615Q-R6V-cLrm
    - url: https://drive.google.com/uc?id=1VJcYHd-yiTnTT-CygM40LxepPC3BJxtL
    - url: https://drive.google.com/uc?id=1lU1tewRohr5vh16wlVqJDJmthVt_NQ8E
    - url: https://drive.google.com/uc?id=1amHDBDhGTLMQDnsg39NCsGbRDFg25oID
    - url: https://drive.google.com/uc?id=11pC7vANkEGUViWmlfo-dfHRiOvSTC7S7
    - url: https://drive.google.com/uc?id=1KDMo26L_77LdNzGFZ4Y1vSGh7cTVPC6u
    - url: https://drive.google.com/uc?id=1k73GQTR7svYiFoSL2g1Lgf6Tn7xYEe9Z
    - url: https://drive.google.com/uc?id=1lmie0tSblSlbv21TLqRvKcrEprnynfwK
  suite_2:
    - url: https://drive.google.com/uc?id=1QU4mNoIXuMR_hgtiBj1f-YOUK5o1aaYc
    - url: https://drive.google.com/uc?id=1jqdbEsDVm7LL6A9hOLqgBiCguBgvz0IN
    - url: https://drive.google.com/uc?id=1qanBmuu-T7Xp_lB5fahP4DqbyhASv-vM
    - url: https://drive.google.com/uc?id=1MQHBEtQ_b2n-Mkaf6C0t7XUIXNqibVcZ
    - url: https://drive.google.com/uc?id=1Rqi6mna6XgAbHeNDICKsyVrdqpRjUZEZ
    - url: https://drive.google.com/uc?id=1cKaKJqch_p12w6-JDq-KW4ZzVFJ1j_fa
    - url: https://drive.google.com/uc?id=1oPaC631NBZYry1lx1n4DDhPdwA6e75wc
    - url: https://drive.google.com/uc?id=1lEQ8Zhl2JFSgsQW3erD_99NHnbdtjxbK
    - url: https://drive.google.com/uc?id=1ptMTyO8zobFeBjY4p_9zkah0dEipw2Ez
    - url: https://drive.google.com/uc?id=1xZgFr1mZM2Sn23-QVZync0jNy0Z1rICZ
    - url: https://drive.google.com/uc?id=1c5MQ0n3_7sCP1L40ijiSC3voOcXA95H8
    - url: https://drive.google.com/uc?id=1DWoqugnXrmfYGHhTsGLstyHsrzUMR23q
    - url: https://drive.google.com/uc?id=1bu7JqSkCIL2PmbDHDs3vfukDEP5OoP1B
    - url: https://drive.google.com/uc?id=1OmKydMSHlkRfQFU2RK_d--4d5hpyESqv
    - url: https://drive.google.com/uc?id=1F1-G1q2vRgJ4Na3uW22sRhedZMOmWkRL
    - url: https://drive.google.com/uc?id=1Yo-rfgUydR1n3kI56lLuK4uWaxizYMXK
    - url: https://drive.google.com/uc?id=1k73GQTR7svYiFoSL2g1Lgf6Tn7xYEe9Z
    - url: https://drive.google.com/uc?id=1lmie0tSblSlbv21TLqRvKcrEprnynfwK
  suite_3:
    - url: https://drive.google.com/uc?id=1tl8HC7QK6wv_9yxr2D1tAdag5pt015jx
    - url: https://drive.google.com/uc?id=1A5phXRaq48Kqrfb7MYLutYjUaxVYx4dU
    - url: https://drive.google.com/uc?id=1sK1OO4hekGwqCeIuqwgb6ZockHrpUCr2
    - url: https://drive.google.com/uc?id=1XQCen25IQrkpWn6GLNZUHrVqOngpVi3w
    - url: https://drive.google.com/uc?id=1aZltFLSDwWQ7oc-4LmHaont87BbNlY7b
    - url: https://drive.google.com/uc?id=1eqK_g8LlqLE-v29t1KKuVQ-abxJNSI2y
    - url: https://drive.google.com/uc?id=1lWGWkYy8Mi6X0Z2L2HZE0HQAT6wG5PDF
    - url: https://drive.google.com/uc?id=1Br3LdvfFR13o_FIrDMb_x8Dt_BgK583x
    - url: https://drive.google.com/uc?id=1hQ5VbOJQaE1MkmE6oIaoY6PeqZBHXKP1
    - url: https://drive.google.com/uc?id=1xCpVzdO8s-t5b1aMwowucP5pxlq5HiYu
    - url: https://drive.google.com/uc?id=16UkLvIa_5riWYqg460GB37_L17KY-Buh
    - url: https://drive.google.com/uc?id=1aDE4A6ZmAmY_PJW3XxsJ3SKthe8_Lari
    - url: https://drive.google.com/uc?id=1TttjUcwAQSD08TUSp-YZMJ60Kj77YhSu
    - url: https://drive.google.com/uc?id=1HXjUy-JdBscCh1QSlag0ZHvQyIF4YiEA
    - url: https://drive.google.com/uc?id=1mVQt7_vJ_zxo-yxelvQXy60ZPghUD9h8
    - url: https://drive.google.com/uc?id=1AUFYcIweGJmQquMuqJnbxi-k9Ky_QM5N
    - url: https://drive.google.com/uc?id=1VOX5GvOF97W_zH3tByYbn27syXoY2pRW
    - url: https://drive.google.com/uc?id=1Y9Es9oPEWztn8zY7ygApaKqzF1TZltrV
    - url: https://drive.google.com/uc?id=1dOwX9S7vmiGkd7So9b3MqfwmeegJGuuG
    - url: https://drive.google.com/uc?id=1k73GQTR7svYiFoSL2g1Lgf6Tn7xYEe9Z
    - url: https://drive.google.com/uc?id=1lmie0tSblSlbv21TLqRvKcrEprnynfwK
