# site settings
title: Misstravel
email: misstravel0921@gmail.com
line: misstravel0921
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
phone: 0905108958
role_url: "infos/2022-10-06-roles.html"
account_url: "infos/2022-10-06-account.html"
set_menu_url: "infos/2022-10-06-set-menu-info.html"
menu_url: "infos/2022-10-06-menu.html"

# homepage tiles
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  Facebook: https://www.facebook.com/misstravel0921

collections:
  rooms:
    output: true
  infos:
    output: true

# build settings
markdown: kramdown
kramdown:
  input: GFM

sass:
  load_paths:
    - _sass
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
